Feature/all properties have explicit defined (#23 fixes)
darraghoriordan/eslint-plugin-nestjs-typed pull request #27
Opened 2022-06-08 15:51 UTC by vic1707

Since the original PR (#23) seems dead I took the liberty to copy the code and fix (I hope) all the requested changes. 

At time of writting I think I just have to split the rule in two as asked in one of the comments.

2022-06-08 21:29 UTC, vic1707 commented
The rules should be working in the current state, but the "non conflicting operators" one can be largely improved and needs to get the lists of incompatible decorators.
@darraghoriordan  do you know if the "typeCheckingDecorator" are all mutually exclusive (like setting `IsString` and `IsBoolean` are obviously incompatible)? If so it would drastically simplify the rule.

2022-06-08 21:29 UTC, vic1707 commented
The rules should be working in the current state, but the "non conflicting operators" one can be largely improved and needs to get the lists of incompatible decorators.
@darraghoriordan  do you know if the "typeCheckingDecorator" are all mutually exclusive (like setting `IsString` and `IsBoolean` are obviously incompatible)? If so it would drastically simplify the rule.

2022-06-27 22:55 UTC, darraghoriordan commented
hey!

I had a look at this and the tests didn't pass on my machine. I downloaded it, `yarn && yarn build && yarn test`

2022-06-28 09:37 UTC, vic1707 commented
tests are now fixed @darraghoriordan.
Before considering the merge I'd still need some clues about the [non conflicting operators](https://github.com/darraghoriordan/eslint-plugin-nestjs-typed/pull/27#issuecomment-1150433379).
Also I'm searching for a way to get the quickfix to figure out the indentation of the code

2022-08-29 09:47 UTC, vic1707 commented
@darraghoriordan do we have an update on this?

2022-09-01 11:00 UTC, darraghoriordan commented
> 

heya! I need a bit of time to understand this one better. no eta unfortunately. I'll try to get to it in Sept 2022 though! 👍

2022-09-01 11:42 UTC, vic1707 commented
okay 👍

2022-10-30 11:49 UTC, vic1707 commented
Hello @darraghoriordan 
I'm not trying to be a pain in the ass or whatever but it's been 1 month since you've said you'll check my PR. Did you got the time to look at it? Maybe you need some help to understand my code?

2022-11-01 01:32 UTC, darraghoriordan commented
> Hello @darraghoriordan I'm not trying to be a pain in the ass or whatever but it's been 1 month since you've said you'll check my PR. Did you got the time to look at it? Maybe you need some help to understand my code?

hey! No sorry I just don't have the time. It's a large PR adding rules to the default set. 

It will take me hours to review and test it and I have too many other things that are higher priority at the moment.

2022-11-04 01:47 UTC, darraghoriordan commented
I've resolved all the conflicts and made some changes. 

Can you merge https://github.com/darraghoriordan/eslint-plugin-nestjs-typed/tree/feature/all-properties-have-explicit-defined in here please

2022-11-04 02:50 UTC, darraghoriordan commented on README.md
> +-   all-defined-property-must-be-decored
i wouldn't say these are security based

new rules should have an explanation also. These ones would need instructions on how to turn on also if not in the recommended set.

2022-11-04 02:55 UTC, darraghoriordan commented on src/utils/classValidatorDecorators.ts
> +    Allow: [],
these lists would be really difficult to maintain.

2022-11-04 03:02 UTC, darraghoriordan commented on src/rules/allOptionnalPropertyMustBeDecored/allOptionnalPropertyMustBeDecored.test.ts
> +ruleTester.run("all-properties-have-explicit-defined", rule, {
this is checking the wrong rule i think

2022-11-04 03:05 UTC, darraghoriordan commented on src/rules/allDefinedPropertyMustBeDecored/allDefinedPropertyMustBeDecored.ts
> +            (decorator.expression.callee.name === "IsDefined" ||
this logic doesn't work on models that are not DTOs. You'd have to check if there was a property with one of the class validator decorators, then assume this is a DTO, then run the rule for all the other properties. I get too many false postivies on a real nestjs project with this as it is

2022-11-04 03:05 UTC, darraghoriordan commented on src/rules/allDefinedPropertyMustBeDecored/allDefinedPropertyMustBeDecored.ts
> +    name: "all-defined-property-must-be-decored",
missing pluralisation convention that's on all other rules for "property"
spelling issue on "decored"

2022-11-04 03:06 UTC, darraghoriordan commented on src/configs/recommended.ts
> +        "@darraghor/nestjs-typed/no-conflicting-decorators": "error",
i'm not sure i'd add these to the default set

2022-11-04 03:06 UTC, darraghoriordan commented on src/utils/classValidatorDecorators.ts
> +export const typeCheckingDecorator = [
i'm going to try to remove the need for these lists completely. They're too difficult to maintain

2022-11-04 03:09 UTC, darraghoriordan requested changes
Hey Vic, thanks for submitting the PR and for your patience. 

There are a few issues with the rule logic in it so i'm going close this. I've added comments to the parts so you can see for yourself but there's no need to fix them. I wont be merging this. 

I've had a look at iddans original PR and I've merged in the latest and changed a few things in there. i have to do some quick checks but I'll use that PR instead of this one to give you the same functionality as intended here.

2022-11-04 03:10 UTC, darraghoriordan commented
see previous comments

2022-11-04 03:10 UTC, closed without merging

2022-11-06 10:23 UTC, vic1707 commented
Okay, thx for the review and the release of the other pr